# docker container run -dit -p 8080:5000 --tmpfs /opt/omd/sites/cmk/tmp:uid=1000,gid=1000 -v monitoring:/omd/sites 
#   --name monitoring -v /etc/localtime:/etc/localtime:ro --restart always checkmk/check-mk-raw:2.0.0-latest
version: "3.9"
services:
  monitoring:
    image: checkmk/check-mk-raw:2.0.0-latest
    ports:
      - "8080:5000"
    volumes:
      - ./monitoring:/omd/sites 
    environment:
      TZ: "Pacific/Auckland"
    tmpfs:
      /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
